import type { BridgeListing } from "@miami-listing-scout/shared";

export const MOCK_LISTINGS: BridgeListing[] = [
  {
    listingId: "MOCK-001",
    mlsId: "A11500001",
    listPrice: 849000,
    listDate: "2026-03-05",
    status: "Active",
    address: {
      full: "1425 Brickell Ave #42C, Miami, FL 33131",
      street: "1425 Brickell Ave #42C",
      city: "Miami",
      state: "FL",
      zip: "33131",
      county: "Miami-Dade",
    },
    property: {
      type: "Condo",
      bedrooms: 2,
      bathrooms: 2,
      bathsFull: 2,
      bathsHalf: 0,
      sqft: 1350,
      lotSize: 0,
      yearBuilt: 2019,
      stories: 1,
      garage: 1,
      pool: true,
      waterfront: false,
      description:
        "Stunning bay view corner unit in luxury Brickell high-rise. Floor-to-ceiling windows, Italian kitchen with Sub-Zero and Wolf appliances, marble master bath with soaking tub. Full amenities including rooftop pool, fitness center, spa, and 24hr concierge. Walking distance to Brickell City Centre and Mary Brickell Village. Ideal for investors — currently rented at $4,200/mo.",
    },
    photos: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    ],
    agent: {
      name: "Maria Rodriguez",
      phone: "305-555-0101",
      email: "maria@miamirealty.com",
      office: "Miami Luxury Realty",
    },
    geo: { lat: 25.7617, lng: -80.1918 },
    dates: {
      listed: "2026-03-05",
      modified: new Date().toISOString(),
    },
    financial: {
      hoaFee: 850,
      taxAmount: 12400,
      taxYear: 2025,
    },
  },
  {
    listingId: "MOCK-002",
    mlsId: "A11500002",
    listPrice: 1275000,
    listDate: "2026-03-06",
    status: "Active",
    address: {
      full: "320 Viscaya Ave, Coral Gables, FL 33134",
      street: "320 Viscaya Ave",
      city: "Coral Gables",
      state: "FL",
      zip: "33134",
      county: "Miami-Dade",
    },
    property: {
      type: "Single Family",
      bedrooms: 4,
      bathrooms: 3,
      bathsFull: 2,
      bathsHalf: 1,
      sqft: 2650,
      lotSize: 7500,
      yearBuilt: 1952,
      stories: 2,
      garage: 2,
      pool: true,
      waterfront: false,
      description:
        "Charming mid-century Coral Gables home on a tree-lined street. Updated kitchen with quartz counters and stainless steel appliances. Original hardwood floors throughout. Large backyard with pool and mature tropical landscaping. New roof 2024, impact windows throughout. Minutes from Miracle Mile shops and restaurants. Top-rated Coral Gables schools.",
    },
    photos: [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
    ],
    agent: {
      name: "Carlos Gutierrez",
      phone: "305-555-0202",
      email: "carlos@gablesproperties.com",
      office: "Gables Properties Group",
    },
    geo: { lat: 25.7498, lng: -80.2623 },
    dates: {
      listed: "2026-03-06",
      modified: new Date().toISOString(),
    },
    financial: {
      taxAmount: 18500,
      taxYear: 2025,
    },
  },
  {
    listingId: "MOCK-003",
    mlsId: "A11500003",
    listPrice: 525000,
    listDate: "2026-03-04",
    status: "Active",
    address: {
      full: "7890 Collins Ave #604, Miami Beach, FL 33141",
      street: "7890 Collins Ave #604",
      city: "Miami Beach",
      state: "FL",
      zip: "33141",
      county: "Miami-Dade",
    },
    property: {
      type: "Condo",
      bedrooms: 1,
      bathrooms: 1,
      bathsFull: 1,
      bathsHalf: 0,
      sqft: 820,
      lotSize: 0,
      yearBuilt: 2008,
      stories: 1,
      garage: 1,
      pool: true,
      waterfront: true,
      description:
        "Direct ocean view 1BR in North Beach boutique building. Recently renovated with porcelain floors, modern kitchen, and large balcony. Building features oceanfront pool, gym, and direct beach access. Short-term rentals allowed — excellent Airbnb potential with projected $3,800/mo gross. Low HOA includes cable, internet, water, and insurance. Walk to Normandy Isle restaurants.",
    },
    photos: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    ],
    agent: {
      name: "David Chen",
      phone: "305-555-0303",
      email: "david@beachsidemiami.com",
      office: "Beachside Miami Realty",
    },
    geo: { lat: 25.8561, lng: -80.1206 },
    dates: {
      listed: "2026-03-04",
      modified: new Date().toISOString(),
    },
    financial: {
      hoaFee: 620,
      taxAmount: 7200,
      taxYear: 2025,
    },
  },
  {
    listingId: "MOCK-004",
    mlsId: "A11500004",
    listPrice: 389000,
    listDate: "2026-03-07",
    status: "Active",
    address: {
      full: "8455 NW 36th St, Doral, FL 33166",
      street: "8455 NW 36th St",
      city: "Doral",
      state: "FL",
      zip: "33166",
      county: "Miami-Dade",
    },
    property: {
      type: "Townhouse",
      bedrooms: 3,
      bathrooms: 2,
      bathsFull: 2,
      bathsHalf: 1,
      sqft: 1680,
      lotSize: 2200,
      yearBuilt: 2016,
      stories: 2,
      garage: 1,
      pool: false,
      waterfront: false,
      description:
        "Modern 3BR townhouse in gated Doral community. Open-concept living with high ceilings, tile floors, and ample natural light. Kitchen with granite counters and stainless steel appliances. Community pool and playground. Close to Doral CityPlace, top-rated charter schools, and major highways. HOA includes exterior maintenance, roof, and common area insurance. Price reduced $20k — motivated seller.",
    },
    photos: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800",
    ],
    agent: {
      name: "Ana Martinez",
      phone: "305-555-0404",
      email: "ana@doralrealestate.com",
      office: "Doral Real Estate Partners",
    },
    geo: { lat: 25.8195, lng: -80.3553 },
    dates: {
      listed: "2026-03-07",
      modified: new Date().toISOString(),
    },
    financial: {
      hoaFee: 310,
      taxAmount: 5800,
      taxYear: 2025,
    },
  },
  {
    listingId: "MOCK-005",
    mlsId: "A11500005",
    listPrice: 1450000,
    listDate: "2026-03-03",
    status: "Active",
    address: {
      full: "3101 S Bayshore Dr, Coconut Grove, FL 33133",
      street: "3101 S Bayshore Dr",
      city: "Coconut Grove",
      state: "FL",
      zip: "33133",
      county: "Miami-Dade",
    },
    property: {
      type: "Single Family",
      bedrooms: 5,
      bathrooms: 4,
      bathsFull: 3,
      bathsHalf: 1,
      sqft: 3400,
      lotSize: 11000,
      yearBuilt: 1965,
      stories: 2,
      garage: 2,
      pool: true,
      waterfront: true,
      description:
        "Rare waterfront home in the heart of Coconut Grove with private dock and direct bay access. Completely renovated in 2023 — new electrical, plumbing, roof, and impact windows. Chef's kitchen with Miele appliances, custom cabinetry. Resort-style backyard with heated pool, summer kitchen, and lush tropical landscaping. Minutes from CocoWalk, Regatta Park, and top private schools. No HOA. Flood zone AE — current flood insurance $3,200/yr.",
    },
    photos: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    agent: {
      name: "Patricia Vega",
      phone: "305-555-0505",
      email: "patricia@groverealty.com",
      office: "Grove Realty International",
    },
    geo: { lat: 25.7283, lng: -80.2378 },
    dates: {
      listed: "2026-03-03",
      modified: new Date().toISOString(),
    },
    financial: {
      taxAmount: 24000,
      taxYear: 2025,
    },
  },
];
